UPDATE LETTER_GRADE SET EXPIRY_DATE = NULL WHERE to_char(EXPIRY_DATE, 'yyyy-mm-dd') = '2099-12-31';
UPDATE MESSAGE_TYPE_CODE SET EXPIRY_DATE = NULL WHERE to_char(EXPIRY_DATE, 'yyyy-mm-dd') = '2099-12-31';
UPDATE SPECIAL_CASE_CODE SET EXPIRY_DATE = NULL WHERE to_char(EXPIRY_DATE, 'yyyy-mm-dd') = '2099-12-31';
UPDATE UNGRAD_REASON_CODE SET EXPIRY_DATE = NULL WHERE to_char(EXPIRY_DATE, 'yyyy-mm-dd') = '2099-12-31';