INSERT INTO PROGRAM_ALGORITHM_RULE (PROGRAM_ALGO_RULE_ID,GRADUATION_PROGRAM_CODE,ALGORITHM_RULE_CODE,SORT_ORDER) VALUES (SYS_GUID(),'2023-PF','EQUIVALENCY_RULE',95);
INSERT INTO PROGRAM_ALGORITHM_RULE (PROGRAM_ALGO_RULE_ID,GRADUATION_PROGRAM_CODE,ALGORITHM_RULE_CODE,SORT_ORDER) VALUES (SYS_GUID(),'2023-EN','EQUIVALENCY_RULE',115);
