INSERT INTO ALGORITHM_RULE_CODE (ALGORITHM_RULE_CODE, RULE_IMPL_NAME, LABEL, DESCRIPTION, ACTIVE_RULE, DISPLAY_ORDER)
VALUES('MIN_ELC_CREDITS_2023_RULE', 'MinElectiveCredits2023Rule', 'Minimum Elective Credits', 'Checks if student earned a minimum of 28 elective credits', 'Y', 570);

UPDATE PROGRAM_ALGORITHM_RULE SET ALGORITHM_RULE_CODE = 'MIN_ELC_CREDITS_2023_RULE'
WHERE GRADUATION_PROGRAM_CODE IN ('2023-EN', '2023-PF')
AND ALGORITHM_RULE_CODE = 'MIN_ELECTIVE_CREDITS_RULE';

UPDATE PROGRAM_ALGORITHM_RULE SET SORT_ORDER=145
WHERE GRADUATION_PROGRAM_CODE='2023-EN', ALGORITHM_RULE_CODE='MATCH_INDIGENOUS_CREDITS_RULE';

UPDATE PROGRAM_ALGORITHM_RULE SET SORT_ORDER=115
WHERE GRADUATION_PROGRAM_CODE='2023-PF', ALGORITHM_RULE_CODE='MATCH_INDIGENOUS_CREDITS_RULE';
