REM INSERTING into ALGORITHM_RULE_CODE
Insert into ALGORITHM_RULE_CODE (ALGORITHM_RULE_CODE,RULE_IMPL_NAME,LABEL,DESCRIPTION,ACTIVE_RULE,DISPLAY_ORDER,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values ('EXCL_ASSMT_AFT_CUTOFF_RULE','ExcludeAssmtAfterAssessmentCutoffRule',' Exclude assmts after Assessment Cutoff Date rule','Assessments taken after the Assessment Cutoff Date will not be used to determine graduation or projected graduation and will not be reported','Y',490,'API_STUDENT_GRADUATION',to_date('22-06-16','RR-MM-DD'),'API_STUDENT_GRADUATION',to_date('22-06-16','RR-MM-DD'));
/

DECLARE
    v_sort INTEGER;
BEGIN
    SELECT MAX(SORT_ORDER) + 10 INTO v_sort FROM PROGRAM_ALGORITHM_RULE;
    FOR x IN (SELECT DISTINCT GRADUATION_PROGRAM_CODE FROM PROGRAM_ALGORITHM_RULE) LOOP
        Insert into PROGRAM_ALGORITHM_RULE (PROGRAM_ALGO_RULE_ID,GRADUATION_PROGRAM_CODE,ALGORITHM_RULE_CODE,SORT_ORDER,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (SYS_GUID(),x.GRADUATION_PROGRAM_CODE,'EXCL_ASSMT_AFT_CUTOFF_RULE',v_sort,'API_STUDENT_GRADUATION',to_date('22-06-16','RR-MM-DD'),'API_STUDENT_GRADUATION',to_date('22-06-16','RR-MM-DD'));
    END LOOP;
END;
/
