--------------------------------------------------------
--  File created - Wednesday-August-04-2021
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LETTER_GRADE
--------------------------------------------------------

CREATE TABLE "LETTER_GRADE"
(	"LETTER_GRADE" VARCHAR2(2 BYTE),
     "PASS_FLAG" VARCHAR2(1 BYTE) NOT NULL ENABLE,
     "GPA_MARK_VALUE" NUMBER(5,4) NOT NULL ENABLE,
     "CREATE_USER" VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "DESCRIPTION" VARCHAR2(250 BYTE),
     CONSTRAINT "LETTER_GRADE_PK" PRIMARY KEY ("LETTER_GRADE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
             TABLESPACE "API_GRAD_DATA"  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;