-- API_STUDENT_GRADUATION.LETTER_GRADE definition

CREATE TABLE "LETTER_GRADE"
   (	"LETTER_GRADE" VARCHAR2(2),
	"PASS_FLAG" VARCHAR2(1) NOT NULL ENABLE,
	"GPA_MARK_VALUE" NUMBER(5,4) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(550),
	"CREATE_USER" VARCHAR2(30) DEFAULT USER NOT NULL ENABLE,
	"CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATE_USER" VARCHAR2(30) DEFAULT USER NOT NULL ENABLE,
	"UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"PERCENT_RANGE_HIGH" NUMBER,
    "PERCENT_RANGE_LOW" NUMBER,
    "LABEL" VARCHAR2(45),
    "EXPIRY_DATE" DATE,
	 CONSTRAINT "LETTER_GRADE_PK" PRIMARY KEY ("LETTER_GRADE")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;