--------------------------------------------------------
--  DDL for Table TRANSCRIPT_MESSAGE
--------------------------------------------------------

CREATE TABLE "TRANSCRIPT_MESSAGE"
(	"TRANSCRIPT_MESSAGE_ID" RAW(16) DEFAULT SYS_GUID(),
     "GRAD_DATE_MESSAGE" VARCHAR2(50 BYTE),
     "GRAD_MAIN_MESSAGE" VARCHAR2(500 BYTE),
     "GRADUATION_PROGRAM_CODE" VARCHAR2(7 BYTE),
     "MESSAGE_TYPE_CODE" VARCHAR2(30 BYTE),
     "AD_IB_PROGRAM_MESSAGE" VARCHAR2(500 BYTE),
     "CAREER_PROGRAM_MESSAGE" VARCHAR2(500 BYTE),
     "PROGRAM_CADRE" VARCHAR2(500 BYTE),
     "HONOUR_NOTE" VARCHAR2(500 BYTE),
     "CREATE_USER" VARCHAR2(32 BYTE) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(32 BYTE) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT "TRANSCRIPT_MESSAGE_PK" PRIMARY KEY ("TRANSCRIPT_MESSAGE_ID")
         USING INDEX
             TABLESPACE "API_GRAD_DATA"  ENABLE,
     CONSTRAINT "FK_MESSAGE_TYPE_CODE" FOREIGN KEY ("MESSAGE_TYPE_CODE")
         REFERENCES "MESSAGE_TYPE_CODE" ("MESSAGE_TYPE_CODE") ENABLE USING INDEX TABLESPACE "API_GRAD_IDX"
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;

