INSERT INTO ALGORITHM_RULE_CODE (ALGORITHM_RULE_CODE, RULE_IMPL_NAME, LABEL, DESCRIPTION, ACTIVE_RULE, DISPLAY_ORDER)
VALUES('MATCH_CREDITS_2023_RULE', 'MatchCredits2023Rule', 'Match Credits for 2023-EN and 2023-PF',
	'Checks if student earned a minimum of 4-credits in one or more eligible courses for a required subject area (i.e., courses listed under the applicable Rule #)', 'Y', 560);

UPDATE PROGRAM_ALGORITHM_RULE SET ALGORITHM_RULE_CODE = 'MATCH_CREDITS_2023_RULE'
WHERE GRADUATION_PROGRAM_CODE IN ('2023-EN', '2023-PF')
AND ALGORITHM_RULE_CODE = 'MATCH_CREDITS_RULE';
