ALTER TABLE UNDO_COMPLETION_REASON_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE UNDO_COMPLETION_REASON_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE TRANSCRIPT_MESSAGE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE TRANSCRIPT_MESSAGE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE STUDENT_UNDO_COMPLETION_REASON
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE STUDENT_UNDO_COMPLETION_REASON
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE SPECIAL_CASE_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE SPECIAL_CASE_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE PROGRAM_ALGORITHM_RULE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE PROGRAM_ALGORITHM_RULE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE LETTER_GRADE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE LETTER_GRADE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE ALGORITHM_RULE_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE ALGORITHM_RULE_CODE
    MODIFY UPDATE_USER VARCHAR2(100);