--------------------------------------------------------
--  DDL for Table UNGRAD_REASON_CODE
--------------------------------------------------------

CREATE TABLE "UNGRAD_REASON_CODE"
(	"UNGRAD_REASON_CODE" VARCHAR2(10 BYTE),
     "LABEL" VARCHAR2(32 BYTE) NOT NULL ENABLE,
     "DESCRIPTION" VARCHAR2(255 BYTE) NOT NULL ENABLE,
     "DISPLAY_ORDER" NUMBER NOT NULL ENABLE,
     "EFFECTIVE_DATE" DATE NOT NULL ENABLE,
     "EXPIRY_DATE" DATE,
     "CREATE_USER" VARCHAR2(32 BYTE) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(32 BYTE) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT "UNGRAD_REASON_CODE_PK" PRIMARY KEY ("UNGRAD_REASON_CODE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
             STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "API_GRAD_DATA"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;

