GRANT SELECT ON ALGORITHM_RULE_CODE TO GRAD_READONLY;
GRANT SELECT ON LETTER_GRADE TO GRAD_READONLY;
GRANT SELECT ON PROGRAM_ALGORITHM_RULE TO GRAD_READONLY;
GRANT SELECT ON SPECIAL_CASE_CODE TO GRAD_READONLY;
GRANT SELECT ON TRANSCRIPT_MESSAGE TO GRAD_READONLY;
GRANT SELECT ON MESSAGE_TYPE_CODE TO GRAD_READONLY;
GRANT SELECT ON STUDENT_UNDO_COMPLETION_REASON TO GRAD_READONLY;
GRANT SELECT ON UNDO_COMPLETION_REASON_CODE TO GRAD_READONLY;
