-- API_STUDENT_GRADUATION.TRANSCRIPT_MESSAGE definition

CREATE TABLE "TRANSCRIPT_MESSAGE"
   (	"TRANSCRIPT_MESSAGE_ID" RAW(16) DEFAULT SYS_GUID(),
	"GRAD_DATE_MESSAGE" VARCHAR2(50),
	"GRAD_MAIN_MESSAGE" VARCHAR2(500),
	"GRADUATION_PROGRAM_CODE" VARCHAR2(7),
	"MESSAGE_TYPE_CODE" VARCHAR2(30),
	"AD_IB_PROGRAM_MESSAGE" VARCHAR2(500),
	"CAREER_PROGRAM_MESSAGE" VARCHAR2(500),
	"PROGRAM_CADRE" VARCHAR2(500),
	"HONOUR_NOTE" VARCHAR2(500),
	"CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
	"CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
	"UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "TRANSCRIPT_MESSAGE_PK" PRIMARY KEY ("TRANSCRIPT_MESSAGE_ID")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE,
	 CONSTRAINT "TRNS_MSG_MSG_TYCD_FK" FOREIGN KEY ("MESSAGE_TYPE_CODE")
	  REFERENCES "MESSAGE_TYPE_CODE" ("MESSAGE_TYPE_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;