/*Transcript Messages*/
/*ROLLBACK
BEGIN
    DELETE FROM API_STUDENT_GRADUATION.TRANSCRIPT_MESSAGE WHERE GRADUATION_PROGRAM_CODE LIKE '%2023%';
END;
*/
/*2023-EN*/
INSERT
INTO API_STUDENT_GRADUATION.TRANSCRIPT_MESSAGE
(TRANSCRIPT_MESSAGE_ID,
 GRAD_DATE_MESSAGE,
 GRAD_MAIN_MESSAGE,
 GRADUATION_PROGRAM_CODE,
 MESSAGE_TYPE_CODE,
 AD_IB_PROGRAM_MESSAGE,
 CAREER_PROGRAM_MESSAGE,
 PROGRAM_CADRE,
 HONOUR_NOTE,
 CREATE_USER,
 CREATE_DATE,
 UPDATE_USER,
 UPDATE_DATE,
 GRAD_PROJECTED_MESSAGE,
 HONOUR_PROJECTED_NOTE,
 GRADUATION_SCHOOL)
VALUES (SYS_GUID(),
        'Graduation Date: %s',
        'Based on the information provided by the school, this student has graduated in the %s.',
        '2023-EN',
        'GRADUATED',
        'This student has also participated in: %s',
        'This student has participated in Career Program(s): %s',
        'This student has also successfully completed the %s Program',
        'Based on the information provided by the school, this student has graduated in the %s with Honours.',
        'API_STUDENT_GRADUATION',
        TIMESTAMP '2021 - 10 - 20 20:01:44.000000',
        'API_STUDENT_GRADUATION',
        TIMESTAMP '2021 - 10 - 20 20:01:44.000000',
        'Based on the information provided by the school, this student should be able to graduate on the %s',
        'Based on the information provided by the school,
        this student should be able to graduate on the %s with honours',
        'Graduation School: %s');

INSERT
INTO API_STUDENT_GRADUATION.TRANSCRIPT_MESSAGE
(TRANSCRIPT_MESSAGE_ID,
 GRAD_DATE_MESSAGE,
 GRAD_MAIN_MESSAGE,
 GRADUATION_PROGRAM_CODE,
 MESSAGE_TYPE_CODE,
 AD_IB_PROGRAM_MESSAGE,
 CAREER_PROGRAM_MESSAGE,
 PROGRAM_CADRE,
 HONOUR_NOTE,
 CREATE_USER,
 CREATE_DATE,
 UPDATE_USER,
 UPDATE_DATE,
 GRAD_PROJECTED_MESSAGE,
 HONOUR_PROJECTED_NOTE,
 GRADUATION_SCHOOL)
VALUES (SYS_GUID(),
        NULL,
        'Based on the information provided by the school,
        this student has not yet graduated in the %s. Students with questions should contact their schools immediately.',
        '2023-EN',
        'NOT_GRADUATED',
        'This student is also participating in: %s',
        'This student is participating in Career Program(s): %s',
        NULL,
        NULL,
        'API_STUDENT_GRADUATION',
        TIMESTAMP '2021 - 10 - 20 20:01:44.000000',
        'API_STUDENT_GRADUATION',
        TIMESTAMP '2021 - 10 - 20 20:01:44.000000',
        'Based on the information provided by the school, this student cannot satisfy the requirements for the %s.',
        NULL,
        NULL);

/*2023-PF*/
INSERT
INTO API_STUDENT_GRADUATION.TRANSCRIPT_MESSAGE
(TRANSCRIPT_MESSAGE_ID,
 GRAD_DATE_MESSAGE,
 GRAD_MAIN_MESSAGE,
 GRADUATION_PROGRAM_CODE,
 MESSAGE_TYPE_CODE,
 AD_IB_PROGRAM_MESSAGE,
 CAREER_PROGRAM_MESSAGE,
 PROGRAM_CADRE,
 HONOUR_NOTE,
 CREATE_USER,
 CREATE_DATE,
 UPDATE_USER,
 UPDATE_DATE,
 GRAD_PROJECTED_MESSAGE,
 HONOUR_PROJECTED_NOTE,
 GRADUATION_SCHOOL)
VALUES (SYS_GUID(),
        'Graduation Date: %s',
        'Based on the information provided by the school, this student has graduated in the %s.',
        '2023 - PF ',
        'GRADUATED',
        'This student has also participated in: %s',
        'This student has participated in Career Program(s): %s',
        'This student has also successfully completed the %s Program',
        'Based on the information provided by the school, this student has graduated in the %s with Honours.',
        'API_STUDENT_GRADUATION',
        TIMESTAMP '2021 - 10 - 20 20:01:44.000000',
        'API_STUDENT_GRADUATION',
        TIMESTAMP '2021 - 10 - 20 20:01:44.000000',
        'Based on the information provided by the school, this student should be able to graduate on the %s',
        'Based on the information provided by the school,
        this student should be able to graduate on the %s with honours',
        'Graduation School: %s');

INSERT
INTO API_STUDENT_GRADUATION.TRANSCRIPT_MESSAGE
(TRANSCRIPT_MESSAGE_ID,
 GRAD_DATE_MESSAGE,
 GRAD_MAIN_MESSAGE,
 GRADUATION_PROGRAM_CODE,
 MESSAGE_TYPE_CODE,
 AD_IB_PROGRAM_MESSAGE,
 CAREER_PROGRAM_MESSAGE,
 PROGRAM_CADRE,
 HONOUR_NOTE,
 CREATE_USER,
 CREATE_DATE,
 UPDATE_USER,
 UPDATE_DATE,
 GRAD_PROJECTED_MESSAGE,
 HONOUR_PROJECTED_NOTE,
 GRADUATION_SCHOOL)
VALUES (SYS_GUID(),
        NULL,
        'Based on the information provided by the school,
        this student has not yet graduated in the %s. Students with questions should contact their schools immediately.',
        '2023 - PF ',
        'NOT_GRADUATED',
        'This student is also participating in: %s',
        'This student is participating in Career Program(s): %s',
        NULL,
        NULL,
        'API_STUDENT_GRADUATION',
        TIMESTAMP '2021 - 10 - 20 20:01:44.000000',
        'API_STUDENT_GRADUATION',
        TIMESTAMP '2021 - 10 - 20 20:01:44.000000',
        'Based on the information provided by the school, this student cannot satisfy the requirements for the %s.',
        NULL,
        NULL);