UPDATE LETTER_GRADE arc SET arc.EXPIRY_DATE = NULL WHERE arc.EXPIRY_DATE = TO_DATE('2099-12-31', 'yyyy-mm-dd');
UPDATE MESSAGE_TYPE_CODE arc SET arc.EXPIRY_DATE = NULL WHERE arc.EXPIRY_DATE = TO_DATE('2099-12-31', 'yyyy-mm-dd');
UPDATE SPECIAL_CASE_CODE arc SET arc.EXPIRY_DATE = NULL WHERE arc.EXPIRY_DATE = TO_DATE('2099-12-31', 'yyyy-mm-dd');
UPDATE UNGRAD_REASON_CODE arc SET arc.EXPIRY_DATE = NULL WHERE arc.EXPIRY_DATE = TO_DATE('2099-12-31', 'yyyy-mm-dd');