package ca.bc.gov.educ.api.studentgraduation.util;

public interface PermissionsContants {
	String _PREFIX = "hasAuthority('";
	String _SUFFIX = "')";

	String READ_GRAD_PROGRAM = _PREFIX + "SCOPE_READ_GRAD_PROGRAM_CODE_DATA" + _SUFFIX;
	String CREATE_GRAD_PROGRAM = _PREFIX + "SCOPE_CREATE_GRAD_PROGRAM_CODE_DATA" + _SUFFIX;
	String UPDATE_GRAD_PROGRAM = _PREFIX + "SCOPE_UPDATE_GRAD_PROGRAM_CODE_DATA" + _SUFFIX;
	String READ_GRAD_PROGRAM_SET = _PREFIX + "SCOPE_READ_GRAD_PROGRAM_SETS_DATA" + _SUFFIX;
	String DELETE_GRAD_PROGRAM = _PREFIX + "SCOPE_DELETE_GRAD_PROGRAM_CODE_DATA" + _SUFFIX;
	String READ_GRAD_PROGRAM_RULES = _PREFIX + "SCOPE_READ_GRAD_PROGRAM_RULES_DATA" + _SUFFIX;
	String READ_GRAD_SPECIAL_CASE = _PREFIX + "SCOPE_READ_GRAD_SPECIAL_CASE_DATA" + _SUFFIX;
	String READ_GRAD_LETTER_GRADE = _PREFIX + "SCOPE_READ_GRAD_LETTER_GRADE_DATA" + _SUFFIX;
	String CREATE_GRAD_PROGRAM_SET = _PREFIX + "SCOPE_CREATE_GRAD_PROGRAM_SETS_DATA" + _SUFFIX;
	String UPDATE_GRAD_PROGRAM_SET = _PREFIX + "SCOPE_UPDATE_GRAD_PROGRAM_SETS_DATA" + _SUFFIX;
	String DELETE_GRAD_PROGRAM_SET = _PREFIX + "SCOPE_DELETE_GRAD_PROGRAM_SETS_DATA" + _SUFFIX;
	String CREATE_GRAD_PROGRAM_RULES = _PREFIX + "SCOPE_CREATE_GRAD_PROGRAM_RULES_DATA" + _SUFFIX;
	String UPDATE_GRAD_PROGRAM_RULES = _PREFIX + "SCOPE_UPDATE_GRAD_PROGRAM_RULES_DATA" + _SUFFIX;
	String DELETE_GRAD_PROGRAM_RULES = _PREFIX + "SCOPE_DELETE_GRAD_PROGRAM_RULES_DATA" + _SUFFIX;
	String READ_GRAD_SPECIAL_PROGRAM = _PREFIX + "SCOPE_READ_GRAD_SPECIAL_PROGRAM_CODE_DATA" + _SUFFIX;
	String CREATE_GRAD_SPECIAL_PROGRAM = _PREFIX + "SCOPE_CREATE_GRAD_SPECIAL_PROGRAM_CODE_DATA" + _SUFFIX;
	String UPDATE_GRAD_SPECIAL_PROGRAM = _PREFIX + "SCOPE_UPDATE_GRAD_SPECIAL_PROGRAM_CODE_DATA" + _SUFFIX;
	String DELETE_GRAD_SPECIAL_PROGRAM = _PREFIX + "SCOPE_DELETE_GRAD_SPECIAL_PROGRAM_CODE_DATA" + _SUFFIX;
	String READ_GRAD_SPECIAL_PROGRAM_RULES = _PREFIX + "SCOPE_READ_GRAD_SPECIAL_PROGRAM_RULES_DATA" + _SUFFIX;
	String CREATE_GRAD_SPECIAL_PROGRAM_RULES = _PREFIX + "SCOPE_CREATE_GRAD_SPECIAL_PROGRAM_RULES_DATA" + _SUFFIX;
	String UPDATE_GRAD_SPECIAL_PROGRAM_RULES = _PREFIX + "SCOPE_UPDATE_GRAD_SPECIAL_PROGRAM_RULES_DATA" + _SUFFIX;
	String DELETE_GRAD_SPECIAL_PROGRAM_RULES = _PREFIX + "SCOPE_DELETE_GRAD_SPECIAL_PROGRAM_RULES_DATA" + _SUFFIX;
	String READ_GRAD_STUDENT_UNGRAD_REASONS_DATA = _PREFIX + "SCOPE_READ_GRAD_STUDENT_UNGRAD_REASONS_DATA" + _SUFFIX;
	String CREATE_GRAD_STUDENT_UNGRAD_REASONS_DATA = _PREFIX + "SCOPE_CREATE_GRAD_STUDENT_UNGRAD_REASONS_DATA" + _SUFFIX;
	String DELETE_UNGRAD_REASON = _PREFIX + "SCOPE_DELETE_GRAD_UNGRAD_CODE_DATA"+ _SUFFIX;
	String UPDATE_UNGRAD_REASON = _PREFIX + "SCOPE_UPDATE_GRAD_UNGRAD_CODE_DATA"+ _SUFFIX;
	String CREATE_UNGRAD_REASON = _PREFIX + "SCOPE_CREATE_GRAD_UNGRAD_CODE_DATA"+ _SUFFIX;
	String READ_GRAD_UNGRAD = _PREFIX + "SCOPE_READ_GRAD_UNGRAD_CODE_DATA" + _SUFFIX;
	String READ_GRAD_MESSAGING = _PREFIX + "SCOPE_READ_GRAD_MESSAGING_CODE_DATA"+ _SUFFIX;
	String READ_GRAD_ALGORITHM_RULES = _PREFIX + "SCOPE_READ_GRAD_ALGORITHM_RULES_DATA" + _SUFFIX;
	String READ_ALGORITHM_DATA = _PREFIX + "SCOPE_READ_GRAD_ALGORITHM_RULES_DATA" + _SUFFIX + " and "
		+ _PREFIX + "SCOPE_READ_GRAD_SPECIAL_CASE_DATA" + _SUFFIX + " and "
		+ _PREFIX + "SCOPE_READ_GRAD_LETTER_GRADE_DATA" + _SUFFIX;
}
