package ca.bc.gov.educ.api.studentgraduation.util;

public interface PermissionsContants {
	String PREFIX = "hasAuthority('";
	String SUFFIX = "')";

	String READ_GRAD_PROGRAM = PREFIX + "SCOPE_READ_GRAD_PROGRAM_CODE_DATA" + SUFFIX;
	String CREATE_GRAD_PROGRAM = PREFIX + "SCOPE_CREATE_GRAD_PROGRAM_CODE_DATA" + SUFFIX;
	String UPDATE_GRAD_PROGRAM = PREFIX + "SCOPE_UPDATE_GRAD_PROGRAM_CODE_DATA" + SUFFIX;
	String READ_GRAD_PROGRAM_SET = PREFIX + "SCOPE_READ_GRAD_PROGRAM_SETS_DATA" + SUFFIX;
	String DELETE_GRAD_PROGRAM = PREFIX + "SCOPE_DELETE_GRAD_PROGRAM_CODE_DATA" + SUFFIX;
	String READ_GRAD_PROGRAM_RULES = PREFIX + "SCOPE_READ_GRAD_PROGRAM_RULES_DATA" + SUFFIX;
	String READ_GRAD_SPECIAL_CASE = PREFIX + "SCOPE_READ_GRAD_SPECIAL_CASE_DATA" + SUFFIX;
	String READ_GRAD_LETTER_GRADE = PREFIX + "SCOPE_READ_GRAD_LETTER_GRADE_DATA" + SUFFIX;
	String CREATE_GRAD_PROGRAM_SET = PREFIX + "SCOPE_CREATE_GRAD_PROGRAM_SETS_DATA" + SUFFIX;
	String UPDATE_GRAD_PROGRAM_SET = PREFIX + "SCOPE_UPDATE_GRAD_PROGRAM_SETS_DATA" + SUFFIX;
	String DELETE_GRAD_PROGRAM_SET = PREFIX + "SCOPE_DELETE_GRAD_PROGRAM_SETS_DATA" + SUFFIX;
	String CREATE_GRAD_PROGRAM_RULES = PREFIX + "SCOPE_CREATE_GRAD_PROGRAM_RULES_DATA" + SUFFIX;
	String UPDATE_GRAD_PROGRAM_RULES = PREFIX + "SCOPE_UPDATE_GRAD_PROGRAM_RULES_DATA" + SUFFIX;
	String DELETE_GRAD_PROGRAM_RULES = PREFIX + "SCOPE_DELETE_GRAD_PROGRAM_RULES_DATA" + SUFFIX;
	String READ_GRAD_SPECIAL_PROGRAM = PREFIX + "SCOPE_READ_GRAD_SPECIAL_PROGRAM_CODE_DATA" + SUFFIX;
	String CREATE_GRAD_SPECIAL_PROGRAM = PREFIX + "SCOPE_CREATE_GRAD_SPECIAL_PROGRAM_CODE_DATA" + SUFFIX;
	String UPDATE_GRAD_SPECIAL_PROGRAM = PREFIX + "SCOPE_UPDATE_GRAD_SPECIAL_PROGRAM_CODE_DATA" + SUFFIX;
	String DELETE_GRAD_SPECIAL_PROGRAM = PREFIX + "SCOPE_DELETE_GRAD_SPECIAL_PROGRAM_CODE_DATA" + SUFFIX;
	String READ_GRAD_SPECIAL_PROGRAM_RULES = PREFIX + "SCOPE_READ_GRAD_SPECIAL_PROGRAM_RULES_DATA" + SUFFIX;
	String CREATE_GRAD_SPECIAL_PROGRAM_RULES = PREFIX + "SCOPE_CREATE_GRAD_SPECIAL_PROGRAM_RULES_DATA" + SUFFIX;
	String UPDATE_GRAD_SPECIAL_PROGRAM_RULES = PREFIX + "SCOPE_UPDATE_GRAD_SPECIAL_PROGRAM_RULES_DATA" + SUFFIX;
	String DELETE_GRAD_SPECIAL_PROGRAM_RULES = PREFIX + "SCOPE_DELETE_GRAD_SPECIAL_PROGRAM_RULES_DATA" + SUFFIX;
	String READ_GRAD_STUDENT_UNGRAD_REASONS_DATA = PREFIX + "SCOPE_READ_GRAD_STUDENT_UNGRAD_REASONS_DATA" + SUFFIX;
	String CREATE_GRAD_STUDENT_UNGRAD_REASONS_DATA = PREFIX + "SCOPE_CREATE_GRAD_STUDENT_UNGRAD_REASONS_DATA" + SUFFIX;
	String DELETE_UNGRAD_REASON = PREFIX + "SCOPE_DELETE_GRAD_UNGRAD_CODE_DATA"+ SUFFIX;
	String UPDATE_UNGRAD_REASON = PREFIX + "SCOPE_UPDATE_GRAD_UNGRAD_CODE_DATA"+ SUFFIX;
	String CREATE_UNGRAD_REASON = PREFIX + "SCOPE_CREATE_GRAD_UNGRAD_CODE_DATA"+ SUFFIX;
	String READ_GRAD_UNGRAD = PREFIX + "SCOPE_READ_GRAD_UNGRAD_CODE_DATA" + SUFFIX;
	String READ_GRAD_MESSAGING = PREFIX + "SCOPE_READ_GRAD_MESSAGING_CODE_DATA"+ SUFFIX;
	String READ_GRAD_ALGORITHM_RULES = PREFIX + "SCOPE_READ_GRAD_ALGORITHM_RULES_DATA" + SUFFIX;
	String READ_ALGORITHM_DATA = PREFIX + "SCOPE_READ_GRAD_ALGORITHM_RULES_DATA" + SUFFIX + " and "
		+ PREFIX + "SCOPE_READ_GRAD_SPECIAL_CASE_DATA" + SUFFIX + " and "
		+ PREFIX + "SCOPE_READ_GRAD_LETTER_GRADE_DATA" + SUFFIX;
}
